import type { LucideIcon } from 'lucide-react'
import {
  Briefcase,
  Laptop,
  TrendingUp,
  Utensils,
  Car,
  Home,
  Heart,
  BookOpen,
  Smile,
  Shirt,
  Settings,
  Circle,
  Wallet,
  ShoppingCart,
  Coffee,
  Dumbbell,
  Plane,
  Fuel,
  Wifi,
  Tv,
  Gift,
  GraduationCap,
  Stethoscope,
  Bus,
  Film,
  Music,
  Palette,
  PiggyBank,
  Landmark,
  Banknote,
  CreditCard,
  Tag,
  type LucideProps,
} from 'lucide-react'

export const CATEGORY_ICON_MAP: Record<string, LucideIcon> = {
  briefcase: Briefcase,
  laptop: Laptop,
  'trending-up': TrendingUp,
  utensils: Utensils,
  car: Car,
  home: Home,
  heart: Heart,
  'book-open': BookOpen,
  smile: Smile,
  shirt: Shirt,
  settings: Settings,
  circle: Circle,
  wallet: Wallet,
  'shopping-cart': ShoppingCart,
  coffee: Coffee,
  dumbbell: Dumbbell,
  plane: Plane,
  fuel: Fuel,
  wifi: Wifi,
  tv: Tv,
  gift: Gift,
  'graduation-cap': GraduationCap,
  stethoscope: Stethoscope,
  bus: Bus,
  film: Film,
  music: Music,
  palette: Palette,
  'piggy-bank': PiggyBank,
  landmark: Landmark,
  banknote: Banknote,
  'credit-card': CreditCard,
  tag: Tag,
}

export const CATEGORY_ICON_KEYS = Object.keys(CATEGORY_ICON_MAP).sort()

export function CategoryIcon({ iconName, className, ...props }: { iconName: string } & LucideProps) {
  const Icon = CATEGORY_ICON_MAP[iconName]
  if (!Icon) return null
  return <Icon className={className} {...props} />
}
